[project]
name = "model_qwen2_5_vl"
version = "0.1.2.dev1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "model-interface @ git+https://github.com/VLMHyperBenchTeam/model_interface.git@0.1.2.dev1"
]

[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["model_qwen2_5_vl"]
