[project]
name = "model-qwen2-5-vl"
version = "0.1.2.dev1"
description = "Qwen2.5-VL model implementation for VLM HyperBench"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "model-interface @ git+https://github.com/VLMHyperBenchTeam/model_interface.git@0.1.2.dev1"
]
authors = [
   {name = "VLMHyperBenchTeam", email = "contact@vlmhyperbench.team"},
   {name = "Anton Shiryaev", email = "med.phisiker@gmail.com"}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["model_qwen2_5_vl"]
