[project]
name = "model-qwen2-5-vl"
version = "0.1.2.dev2"
description = "Qwen2.5-VL model implementation for VLM HyperBench"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "model-interface @ git+https://github.com/VLMHyperBenchTeam/model_interface.git"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["model_qwen2_5_vl"]
