[project]
name = "model-qwen2-5-vl"
version = "0.1.2.dev3"
description = "Qwen2.5-VL model implementation for VLM HyperBench"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "model-interface",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "transformers>=4.37.0",
    "accelerate>=0.20.0",
    "qwen-vl-utils>=0.0.1",
]
authors = [
   {name = "VLMHyperBenchTeam", email = "contact@vlmhyperbench.team"},
   {name = "Anton Shiryaev", email = "med.phisiker@gmail.com"}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["model_qwen2_5_vl"]

[tool.uv.sources]
model-interface = { workspace = true }
